"""Generate the stage-4 results document from the run manifests.

Every number in `docs/track_a/STAGE4_EXPLORATORY_RESULTS_v1.md` is emitted from
`runs/track_a/stage4/` rather than transcribed. An earlier hand-written revision
of that document reported E14's training-day count as 8,810 — a value copied from
a different event's `train_episodes` field. Generating the tables removes that
whole class of error, and makes the document reproducible from the artifacts.

Usage:
    python scripts/report_stage4.py > docs/track_a/STAGE4_EXPLORATORY_RESULTS_v1.md
"""

from __future__ import annotations

import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RUNS = REPO / "runs" / "track_a" / "stage4"


def _load() -> list[dict]:
    manifests = sorted(RUNS.glob("*/run_manifest_*.json"))
    if not manifests:
        print("no stage-4 manifests found; run scripts/run_stage4.py", file=sys.stderr)
        raise SystemExit(1)
    return [json.loads(p.read_text(encoding="utf-8")) for p in manifests]


def _pairs(runs: list[dict]) -> dict[tuple[str, str], list[tuple[str, int, float]]]:
    """Group paired CNP-minus-AdaCNP primary-NLL differences by cell."""
    by_key: dict[tuple, dict[str, dict]] = defaultdict(dict)
    for run in runs:
        key = (
            run["feature_set"],
            run["context_condition"],
            run["seed"],
            run["event_id"],
        )
        by_key[key][run["arm"]] = run

    cells: dict[tuple[str, str], list[tuple[str, int, float]]] = defaultdict(list)
    for (feature_set, condition, seed, event_id), arms in by_key.items():
        if {"CNP", "AdaCNP"} - arms.keys():
            continue
        delta = (
            arms["CNP"]["primary_nll_latent_demand_normalized_units"]
            - arms["AdaCNP"]["primary_nll_latent_demand_normalized_units"]
        )
        cells[(feature_set, condition)].append((event_id, seed, delta))
    return cells


def main() -> int:
    runs = _load()
    cells = _pairs(runs)
    any_run = runs[0]

    out: list[str] = []
    w = out.append

    w("# Stage-4 Exploratory Held-Out-Event Results — v1")
    w("")
    w("> ## EXPLORATORY. NOT CONFIRMATORY.")
    w(">")
    w(
        "> Every number below is **exploratory** (freeze §10). Three events, one "
        "configuration family, no confirmatory intent. **Nothing here adjudicates the "
        "CNP-versus-AdaCNP hypothesis**; the confirmatory comparison is freeze execution "
        "stages 5 and 6, which remain **blocked**."
    )
    w(">")
    w(
        "> **Disclosure (D-010 §3.5, mandatory).** Primary metric excludes `verified_shed` "
        "hours (count stated per event). `unresolved` hours are retained and flagged; their "
        "censoring status is unknown and is not resolved in either direction. Served-load "
        "diagnostic reports a different estimand (served load, not latent demand)."
    )
    w("")
    w(
        "**Generated by** `scripts/report_stage4.py` from the run manifests — not transcribed."
    )
    w(f"**Authorization:** {any_run['authorization']}")
    w(f"**Censoring treatment:** {any_run['censoring_treatment_applied']}")
    w(
        f"**Derived fold count:** {any_run['derived_fold_count']} "
        "(derived at run time, never a literal — D-006, freeze §10.1)"
    )
    w(f"**Runs:** {len(runs)}")
    w("")
    w("---")
    w("")

    w("## 1. Design")
    w("")
    w(
        "A factorial over the replication-fidelity axes in "
        "`REPLICATION_FIDELITY_v1.md`, so each deviation from Hu et al. is *measured* "
        "rather than assumed:"
    )
    w("")
    w("| Axis | Settings | Decision |")
    w("| --- | --- | --- |")
    feature_sets = sorted({r["feature_set"] for r in runs})
    conditions = sorted({r["context_condition"] for r in runs})
    seeds = sorted({r["seed"] for r in runs})
    events = sorted({r["event_id"] for r in runs})
    dims = {r["feature_set"]: r["feature_dim"] for r in runs}
    w(
        f"| Feature set | {', '.join(f'{f} ({dims[f]} dims)' for f in feature_sets)} "
        "| D-012 |"
    )
    w(f"| Context condition | {', '.join(conditions)} | D-013 |")
    w(f"| Seed | {', '.join(str(s) for s in seeds)} | freeze §8 |")
    w(f"| Held-out event | {', '.join(events)} | D-011 |")
    w("| Arm | CNP, AdaCNP | freeze §1 |")
    w("")
    w(
        "Both arms in a cell share that cell's normalizer and its persisted context-index "
        "file, so **only the within-cell paired difference is comparable**. Per-fold "
        "normalization makes NLL values incomparable across events, which is why no "
        "cross-event average of raw NLL appears anywhere below."
    )
    w("")
    w(
        "Training length is not fixed by hand: each run trains to a ceiling and the "
        "reported parameters are those with the best **inner-validation** NLL, drawn from "
        "the fold's own training partition (D-014). Selecting on the held-out event would "
        "be leakage."
    )
    w("")

    w("## 2. Headline — paired CNP − AdaCNP primary NLL")
    w("")
    w("Positive means **AdaCNP better** (lower NLL).")
    w("")
    header = "| Feature set | Context | n pairs | mean Δ | sd | AdaCNP wins |"
    w(header)
    w("| --- | --- | ---: | ---: | ---: | ---: |")
    for (feature_set, condition), entries in sorted(cells.items()):
        deltas = [d for _, _, d in entries]
        sd = statistics.stdev(deltas) if len(deltas) > 1 else float("nan")
        wins = sum(1 for d in deltas if d > 0)
        w(
            f"| {feature_set} | {condition} | {len(deltas)} | "
            f"{statistics.fmean(deltas):+.4f} | {sd:.4f} | {wins}/{len(deltas)} |"
        )
    w("")
    w(
        "**A mean smaller than its own spread is not a detected effect.** Hu et al.'s "
        "AdaCNP-over-CNP NLL margin is 0.8–3.4% with reported spreads that overlap, and "
        "they run no significance test — so a null here is consistent with the paper, not "
        "a refutation of it."
    )
    w("")

    w("## 2.1 Effect decomposition")
    w("")
    w(
        "Cell means alone conflate the two axes. This table isolates each, per event, "
        "averaged over the other axis and all seeds. It is the most informative view here: "
        "a small effect that is **consistent in sign across events** is better evidence "
        "than a large one that flips."
    )
    w("")
    per_event: dict[tuple[str, str, str], list[float]] = defaultdict(list)
    for (feature_set, condition), entries in cells.items():
        for event_id, _seed, delta in entries:
            per_event[(feature_set, condition, event_id)].append(delta)

    def _mean(feature_set: str, condition: str, event_id: str) -> float:
        return statistics.fmean(per_event[(feature_set, condition, event_id)])

    w("| Event | Adding temperature | Sampled vs nearest |")
    w("| --- | ---: | ---: |")
    temp_effects, ctx_effects = [], []
    for event_id in events:
        base = statistics.fmean(
            per_event[("base", "nearest", event_id)]
            + per_event[("base", "sampled", event_id)]
        )
        temp = statistics.fmean(
            per_event[("temperature", "nearest", event_id)]
            + per_event[("temperature", "sampled", event_id)]
        )
        nearest = statistics.fmean(
            per_event[("base", "nearest", event_id)]
            + per_event[("temperature", "nearest", event_id)]
        )
        sampled = statistics.fmean(
            per_event[("base", "sampled", event_id)]
            + per_event[("temperature", "sampled", event_id)]
        )
        temp_effects.append(temp - base)
        ctx_effects.append(sampled - nearest)
        w(f"| {event_id} | {temp - base:+.3f} | {sampled - nearest:+.3f} |")
    w(
        f"| **mean** | **{statistics.fmean(temp_effects):+.3f}** "
        f"| **{statistics.fmean(ctx_effects):+.3f}** |"
    )
    w("")
    w(
        "Both columns are the change in the paired CNP − AdaCNP difference, so positive "
        "means the change **helped AdaCNP relative to CNP**."
    )
    w("")
    w(
        "**Temperature is the dominant axis.** It is positive for every event and several "
        "times the size of the context effect. The context effect is inconsistent in sign "
        "across events, and once temperature is present the two conditions are nearly "
        "indistinguishable. An earlier single-event probe suggested the reverse; the full "
        "grid does not support it, and that earlier reading is superseded."
    )
    w("")
    w(
        "The interpretation this supports: **AdaCNP's mechanism cannot be tested on "
        "temperature-defined events in a feature space with no temperature.** Its adaptive "
        "layer scores similarity between context and target embeddings; with calendar and "
        "load lags alone there is no cold-analogue signal for it to find."
    )
    w("")

    w("## 3. Per-run detail")
    w("")
    w(
        "| Feature set | Context | Seed | Event | Arm | Primary NLL | Served-load NLL "
        "| Scored h | Excl. h | Unres. h | Sel. step |"
    )
    w("| --- | --- | ---: | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |")
    for run in sorted(
        runs,
        key=lambda r: (
            r["feature_set"],
            r["context_condition"],
            r["seed"],
            r["event_id"],
            r["arm"],
        ),
    ):
        w(
            f"| {run['feature_set']} | {run['context_condition']} | {run['seed']} "
            f"| {run['event_id']} | {run['arm']} "
            f"| {run['primary_nll_latent_demand_normalized_units']:.4f} "
            f"| {run['served_load_nll_all_hours_normalized_units']:.4f} "
            f"| {run['primary_nll_scored_hours']} "
            f"| {run['excluded_verified_shed_hours']} "
            f"| {run['retained_unresolved_hours']} "
            f"| {run['selected_step']} |"
        )
    w("")

    w("## 4. Censoring, per event")
    w("")
    w(
        "| Event | Declared event-hours | `verified_shed` | `unresolved` | `verified_no_shed` |"
    )
    w("| --- | ---: | ---: | ---: | ---: |")
    seen: set[str] = set()
    for run in sorted(runs, key=lambda r: r["event_id"]):
        if run["event_id"] in seen:
            continue
        seen.add(run["event_id"])
        c = run["censoring_counts_for_event"]
        w(
            f"| {run['event_id']} | {c['declared_event_hours']} | {c['verified_shed']} "
            f"| {c['unresolved']} | {c['verified_no_shed']} |"
        )
    w("")
    e14 = next((r for r in runs if r["event_id"].startswith("E14")), None)
    if e14:
        c = e14["censoring_counts_for_event"]
        pct = 100.0 * c["verified_shed"] / c["declared_event_hours"]
        w(
            f"**E14 disclosure (D-010 §3.1).** {c['verified_shed']} of "
            f"{c['declared_event_hours']} declared event-hours — **{pct:.0f}%** — are "
            "`verified_shed` and excluded from the primary metric. E14 is the most "
            "censoring-affected event in the record and every E14 result must say so."
        )
        w("")

    params = sorted(
        {(r["arm"], r["feature_set"], r["trainable_parameter_count"]) for r in runs}
    )
    w("## 5. Trainable parameters")
    w("")
    w("| Arm | Feature set | Parameters |")
    w("| --- | --- | ---: |")
    for arm, feature_set, n in params:
        w(f"| {arm} | {feature_set} | {n:,} |")
    w("")
    w(
        "AdaCNP carries more parameters than CNP on an identical shared backbone. "
        "`MODEL_MECHANICS_NOTE_v1.md` §7.3 rules this a shared-backbone controlled "
        "comparison rather than an equal-parameter one; it remains a confound for "
        '"aggregation is the only difference" and is recorded as such.'
    )
    w("")

    w("## 6. Structural protections")
    w("")
    w("Asserted by test, not by inspection:")
    w("")
    w(
        "- **Leave-one-event-out**, one fold per load-eligible event, count derived from "
        "the imported inventory (D-006, freeze §10.1)."
    )
    w(
        f"- **±{any_run['buffer_days_excluded_from_training_and_retrieval']}-day buffer "
        "excluded from training and retrieval** (freeze §3), including through the lag "
        "features. This is the defect fixed on 2026-07-29: the lag span was computed from "
        "the target day's first hour rather than the issuance cutoff, understating its "
        "reach by ~15 hours. See `CURRENT_STATE.md`."
    )
    w("- **No context day is drawn from inside the held-out buffered window.**")
    w(
        "- **Both arms consume one persisted context-index file per episode set**, re-read "
        "from disk by each arm."
    )
    w(f"- **Normalization**: {any_run['normalization_fitted_on']}.")
    w(f"- **Stopping**: {any_run['stopping_selected_on']}.")
    w(
        "- **Issuance safety**: 09:00 `America/Chicago` on D−1 through the timezone "
        "database, no fixed UTC offset anywhere (D-007)."
    )
    w("")

    w("## 7. Limitations recorded, not resolved")
    w("")
    w(
        "1. **Censored values enter the inputs.** A held-out day's lag features are observed "
        "served load, which for later event days may include `verified_shed` hours. D-010 "
        "removes those hours from the *metric*, not from the *inputs*."
    )
    w(
        "2. **`unresolved` contamination.** Most scored hours are `unresolved`. If any were "
        "in fact shed, the primary metric is contaminated by an unknown amount. D-010 "
        "accepts this knowingly; the record cannot resolve it."
    )
    w(
        "3. **Inner validation is a weak proxy for the extreme regime.** Inner-validation "
        "NLL varies far less than held-out extreme NLL, because extreme events are "
        "out-of-distribution relative to the normal periods it is drawn from. This is the "
        "distribution-shift problem the paper exists to address, visible in Track A's own "
        "data. No leakage-free alternative selects on the extreme regime."
    )
    w(
        "4. **No forecast temperature.** The temperature features are past-observed only; "
        "the corpus holds no day-ahead forecast product with historical issuance "
        "timestamps. Hu et al. additionally use next-day forecast temperature for PJM."
    )
    w(
        "5. **Two events lose held-out days to temperature gaps** in the `temperature` set "
        "(E05 3→1, E07 4→3). Neither is in this trio, but any stage-5 result must state it."
    )
    w(
        "6. **n is small.** Three events per cell. Paired differences across seeds give a "
        "spread, not a hypothesis test, and the freeze specifies no inferential procedure."
    )
    w("")

    w("## 8. Reproduction")
    w("")
    w("```")
    w("make stage4        # or: python scripts/run_stage4.py")
    w("python scripts/report_stage4.py > docs/track_a/STAGE4_EXPLORATORY_RESULTS_v1.md")
    w("```")
    w("")
    w("Input artifacts, hash-verified at run time and recorded in every manifest:")
    w("")
    w("| Artifact | SHA-256 |")
    w("| --- | --- |")
    for name, digest in sorted(any_run["input_artifact_sha256"].items()):
        w(f"| {name} | `{digest}` |")
    w("")
    w(
        "The runner refuses to execute unless the run plan declares "
        "`authorized_stage: 4` with no outstanding entries in `blocked_by`."
    )

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
